### PR TITLE
Omnirepo rpm

### PR DESCRIPTION
**Pull request by heitorPB**

### CODE REVIEW

**Review by jamesbeedy — APPROVED** [review]
Works for me - https://paste.ubuntu.com/p/VvgfQqgpdr/

And I see that `slurm-slurmctld` comes from the omni repo https://paste.ubuntu.com/p/gg6nN3vhqG/

LGTM 👍

**Review by jamesbeedy — COMMENTED** [review]
Why use `subprocess.check_output()` if we aren’t doing anything with the output?

**Comment by heitorPB** [comment]
> Why use `subprocess.check_output()` if we aren’t doing anything with the output?

It raises an exception when the command fails. We were hitting a bug that one of those commands failed some time ago. We could do something with the output as well, if you want.

**Review by jamesbeedy — APPROVED** [review]
👍

**Pull request merged**
